---
title: "asreml results for Jane Manfredi"
author: "Aaron Rendahl, PhD"
date: "March 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(knitr)
library(dplyr)
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot(font_size=8))

figw <- 8/2.54
figh <- figw*0.8
fudge <- 0.352777778

```

Results from Rob's computer, using R version 3.3.1 (2016-06-21) and asreml 3.0.

### Wald tests
```{r}
w <- read.csv("results-wald.csv", as.is=TRUE)
w %>% kable(digits=c(0,0,2,0,4))
```

### plots
```{r}
d <- read.csv("results-fit.csv", as.is=TRUE)
d$p <- d$predicted.value
d$lo <- d$predicted.value - d$standard.error
d$hi <- d$predicted.value + d$standard.error
d$p <- ifelse(d$response=="insulin", exp(d$p), d$p)
d$lo <- ifelse(d$response=="insulin", exp(d$lo), d$lo)
d$hi <- ifelse(d$response=="insulin", exp(d$hi), d$hi)
d$var0 <- d$var
d$var[d$var=="AGE"] <- "Age"
d$var[d$var=="SEX"] <- "Sex"
d$var[d$var=="EMS"] <- "IR"
d$var[d$var=="Adiponectin"] <- "HMW Adiponectin"
d$level[d$level=="n"] <- "No"
d$level[d$level=="y"] <- "Yes"
d$level <- factor(d$level)

ds <- split(d, d[,c("response", "var")])
ds <- lapply(ds, droplevels)

## put plots in the starting order
foo <- unique(d[,c("response", "var")])
foo$v <- paste(foo$response, foo$var, sep=".")
stopifnot(foo$v %in% names(ds))
foo$var <- factor(foo$var, levels=unique(foo$var))
foo <- foo[order(foo$var, foo$response),]
ds <- ds[foo$v]

## for continuous variables, make level names numeric again
## add new column to say if numeric
level.numeric <- rep(FALSE, length(ds))
names(level.numeric) <- names(ds)
for(i in seq_along(ds)) {
  levs <- levels(ds[[i]]$level)
  foo <- as.numeric(levs)
  if(!any(is.na(foo))) {
    level.numeric[i] <- TRUE
    foo <- data.frame(levs=levs, num=foo, round=round(foo, 2))
    foo <- foo[order(foo$num),]
    ds[[i]]$level <- factor(ds[[i]]$level, levels=foo$levs, labels=foo$round)
  }
}

## make the plots
ps <- lapply(seq_along(ds), function(i) {
  p <- ggplot(ds[[i]]) + 
    aes(time, p, ymin=lo, ymax=hi, group=level, linetype=level) + 
    geom_ribbon(alpha=0.3, linetype=0) +
    geom_line() +
    scale_x_continuous(breaks=(0:6)*30, expand=c(0,0)) +
    xlab("Minutes") +
    theme(legend.title=element_blank(), 
          legend.position=c(-0.01, 1.07), 
          legend.justification=c(0, 1),
          legend.key.height = unit(0.6, "line"))
  if(nlevels(ds[[i]]$level)==1) {
    p <- p + guides(linetype=FALSE)
  }
  rr <- ds[[i]]$response[1]
  if(rr=="insulin") p <- p + ylab(expression(paste("Insulin (",mu,"IU/mL)")))
  if(rr=="glucose") p <- p + ylab("Glucose (mg/dL)")
  p <- p + theme(plot.margin = unit(c(4,8,4,4), "pt"))
})
names(ps) <- names(ds)

## add labels to Breed plots
tmp <- subset(ds$insulin.Breed, time==60, select=c(level, p, time))
ps$insulin.Breed <- ps$insulin.Breed + 
  geom_text(aes(x=time, y=p, label=level), data=tmp, inherit.aes=FALSE, size=8*fudge)
tmp <- subset(ds$glucose.Breed, time==120, select=c(level, p, time))
ps$glucose.Breed <- ps$glucose.Breed + 
  geom_text(aes(x=time, y=p, label=level), data=tmp, inherit.aes=FALSE, size=8*fudge)
```


```{r, fig.width=figw, fig.height=figh}
units <- as.data.frame(t(matrix(c(
"Age", "years",
"Leptin", "ng/mL",
"AIRg", "[mU/L]/min"), nrow=2)), stringsAsFactors=FALSE)
names(units) <- c("v", "u")

for(i in seq_along(ds)) {
  var <- ds[[i]]$var[1]
  levs <- levels(ds[[i]]$level)
  if(level.numeric[i]) { # if numeric
    if(var %in% units$v) { # if easy units
      my.labs <- sprintf("%s = %s %s (%s)", var, levs, units$u[units$v==var], c("mean", "mean + SD"))
    } else { # custom units
      if(var=="HMW Adiponectin") {
        my.labs <- list(bquote(.(var) == .(levs[1])~paste(mu, "g/mL")~"(mean)"), 
                        bquote(.(var) == .(levs[2])~paste(mu, "g/mL")~"(mean + SD)"))
      }
      if(var=="SI") {
        my.labs <- list(bquote(.(var) == .(levs[1])~(L/min/mU)/10^4~.("(mean)")), 
                        bquote(.(var) == .(levs[2])~(L/min/mU)/10^4~.("(mean + SD)")))        
      }
    }
  } else { # not numeric
    my.labs <- paste(var, levs)
  }
  ps[[i]] <- ps[[i]] + scale_linetype_manual(values=seq_along(levs), breaks=levs, labels=my.labs)
  plot(ps[[i]]) ## need to run this, otherwise have lazy loading problem
}
```


```{r}
## make y-axes consistent
v1 <- c("Age", "Sex", "Breed")
v2 <- c("IR", "SI", "AIRg")
v3 <- c("HMW Adiponectin", "Leptin")
vars <- c(v1, v2, v3)
foo <- subset(d, response=="insulin" & var %in% vars)
yi <- range(c(foo$lo, foo$hi))
foo <- subset(d, response=="glucose" & var %in% vars)
yg <- range(c(foo$lo, foo$hi))
for(i in grep("insulin", names(ps))) ps[[i]] <- ps[[i]] + ylim(yi)
for(i in grep("glucose", names(ps))) ps[[i]] <- ps[[i]] + ylim(yg)
```

```{r}
ps0 <- ps
```

```{r}
ps <- ps0

## add p-values
w$pval <- ifelse(w$P<0.0001, "p < 0.0001", paste("p = ", formatC(w$P, 2, format="g", flag="#")))
y2 <- 0.89
y5 <- 0.7

for(i in seq_along(ps)) {
  var0 <- ds[[i]]$var0[1]
  res <- ds[[i]]$response[1]
  pv <- w$pval[w$response==res & w$var==var0]
  nlev <- nlevels(ds[[i]]$level)
  ym <- if(res=="insulin") yi else yg
  yp <- if(nlev==5) y5 else y2
  yy <- ym[1] + diff(ym)*yp
  ps[[i]] <- ps[[i]] + annotate("text", x=5, y=yy, label=pv, size=8*fudge, hjust=0)
}
```


```{r}
## output to files

vv <- outer(c("insulin", "glucose"), v1, paste, sep=".")
pp <- cowplot::plot_grid(plotlist=ps[vv], ncol=2, labels="AUTO")
cowplot::save_plot("p1.pdf", pp, base_width=nrow(vv)*figw, base_height=ncol(vv)*figh)
cowplot::save_plot("p1.tiff", pp, base_width=nrow(vv)*figw, base_height=ncol(vv)*figh, compression="lzw")

vv <- outer(c("insulin", "glucose"), v2, paste, sep=".")
pp <- cowplot::plot_grid(plotlist=ps[vv], ncol=2, labels="AUTO")
cowplot::save_plot("p2.pdf", pp, base_width=nrow(vv)*figw, base_height=ncol(vv)*figh)
cowplot::save_plot("p2.tiff", pp, base_width=nrow(vv)*figw, base_height=ncol(vv)*figh, compression="lzw")

vv <- outer(c("insulin", "glucose"), v3, paste, sep=".")
pp <- cowplot::plot_grid(plotlist=ps[vv], ncol=2, labels="AUTO")
cowplot::save_plot("p3.pdf", pp, base_width=nrow(vv)*figw, base_height=ncol(vv)*figh)
cowplot::save_plot("p3.tiff", pp, base_width=nrow(vv)*figw, base_height=ncol(vv)*figh, compression="lzw")

```
